# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MermaidPreviewCli < Formula
  desc "CLI tool for previewing Mermaid diagrams"
  homepage "https://github.com/mxcoppell/mermaid-preview-cli"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v1.0.0/mermaid-preview-cli_1.0.0_darwin_amd64.tar.gz"
    sha256 "e98a03e3ccf42a9b245338576bf09c0cf9fdbc546b0043b721d97760fbe9b547"

    define_method(:install) do
      bin.install "mermaid-preview-cli"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v1.0.0/mermaid-preview-cli_1.0.0_darwin_arm64.tar.gz"
    sha256 "30fb9f290cdd7826ab3bfc4b81bab042cbee808e6a315e07503833d15465ca54"

    define_method(:install) do
      bin.install "mermaid-preview-cli"
    end
  end
end
