# This file was generated by GoReleaser. DO NOT EDIT.
cask "md-preview-cli" do
  name "md-preview-cli"
  desc "CLI tool for previewing markdown files in a native window"
  homepage "https://github.com/mxcoppell/md-preview-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md-preview-cli"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/md-preview-cli/releases/download/v#{version}/md-preview-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "ba6bd65beaec451ff5782b3e1a072604d1194d6f051649d35b33237b2d6d88bd"
    end
    on_arm do
      url "https://github.com/mxcoppell/md-preview-cli/releases/download/v#{version}/md-preview-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "06dee542480e1f1bfce2001c2519e8abe71dadb1fc6f93a4ff58c89280a25732"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md-preview-cli"]
    end
  end

  # No zap stanza required
end
