# This file was generated by GoReleaser. DO NOT EDIT.
cask "md-preview-cli" do
  name "md-preview-cli"
  desc "CLI tool for previewing markdown files in a native window"
  homepage "https://github.com/mxcoppell/md-preview-cli"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md-preview-cli"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/md-preview-cli/releases/download/v#{version}/md-preview-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "50751cdb9755dc196d161ee06a1b5c9a6ee2d6af307591e667c0b838b22f3975"
    end
    on_arm do
      url "https://github.com/mxcoppell/md-preview-cli/releases/download/v#{version}/md-preview-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "4ba5b079fab266cce2eafe9f71f5bc62cd075c0d85689aaa7cdb91d1588eabe0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md-preview-cli"]
    end
  end

  # No zap stanza required
end
