# This file was generated by GoReleaser. DO NOT EDIT.
cask "md-preview-cli" do
  name "md-preview-cli"
  desc "CLI tool for previewing markdown files in a native window"
  homepage "https://github.com/mxcoppell/md-preview-cli"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md-preview-cli"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/md-preview-cli/releases/download/v#{version}/md-preview-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "d2a1f4f600a198c977e2c6534190df910a31f678b93acfa8ed979a2f28e1583d"
    end
    on_arm do
      url "https://github.com/mxcoppell/md-preview-cli/releases/download/v#{version}/md-preview-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "6fa9dab6fc1e9b54b59dde116f2d8fb16bd8dac611fcd86ca15653019011241e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md-preview-cli"]
    end
  end

  # No zap stanza required
end
