# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  version "1.4.0"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/mdp/releases/download/v#{version}/mdp_#{version}_darwin_amd64.tar.gz"
      sha256 "8899a1778d469f600a138561aafedc611d342a80b57a3651ca0ca7c2eff0096f"
    end
    on_arm do
      url "https://github.com/mxcoppell/mdp/releases/download/v#{version}/mdp_#{version}_darwin_arm64.tar.gz"
      sha256 "25f044269be78fb5d036654515fece688ade048bf5ea095955ae8b4b8f4212ed"
    end
  end

  name "mdp"
  desc "CLI tool for previewing markdown files in a native window"
  homepage "https://github.com/mxcoppell/mdp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdp"]
    end
  end

  # No zap stanza required

end
