# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  name "mdp"
  desc "CLI tool for previewing markdown files in a native window"
  homepage "https://github.com/mxcoppell/mdp"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/mdp/releases/download/v#{version}/mdp_#{version}_darwin_amd64.tar.gz"
      sha256 "af6b2b38a79874d2923eec8d2ae2655a193bdf28825c3868c1c65c34e8abd2cd"
    end
    on_arm do
      url "https://github.com/mxcoppell/mdp/releases/download/v#{version}/mdp_#{version}_darwin_arm64.tar.gz"
      sha256 "c85e32b23547da8df752b604a3a263429034b21f6a54ee87252a2b40b8332a8b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdp"]
    end
  end

  # No zap stanza required
end
