# This file was generated by GoReleaser. DO NOT EDIT.
cask "mermaid-preview-cli" do
  name "mermaid-preview-cli"
  desc "CLI tool for previewing Mermaid diagrams"
  homepage "https://github.com/mxcoppell/mermaid-preview-cli"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mermaid-preview-cli"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v#{version}/mermaid-preview-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "72f3b0e4bbc8e0e43f1f205c0fb7ea7024780a61428a7a234ffab2d9819f68f9"
    end
    on_arm do
      url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v#{version}/mermaid-preview-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "5c58cc505db3601ed34120f66f680bc62cb824e8e31bdda7729d09f6c7b323e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mermaid-preview-cli"]
    end
  end

  # No zap stanza required
end
