# This file was generated by GoReleaser. DO NOT EDIT.
cask "mermaid-preview-cli" do
  name "mermaid-preview-cli"
  desc "CLI tool for previewing Mermaid diagrams"
  homepage "https://github.com/mxcoppell/mermaid-preview-cli"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mermaid-preview-cli"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v#{version}/mermaid-preview-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "d0fc966e66dc64eb5ee1dfb976b5b0166b55fc5847664d481225717b8b742297"
    end
    on_arm do
      url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v#{version}/mermaid-preview-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "876939cdabd1271f8a3dfd52dce98ff4ca3a0c07e8e31c92b4bfd39dae3bd1ee"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mermaid-preview-cli"]
    end
  end

  # No zap stanza required
end
