# This file was generated by GoReleaser. DO NOT EDIT.
cask "mermaid-preview-cli" do
  name "mermaid-preview-cli"
  desc "CLI tool for previewing Mermaid diagrams"
  homepage "https://github.com/mxcoppell/mermaid-preview-cli"
  version "1.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mermaid-preview-cli"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v#{version}/mermaid-preview-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "9c55f993e3df145c6dcc965bdf199755593cdd81b31a77a31f7b348eddad842a"
    end
    on_arm do
      url "https://github.com/mxcoppell/mermaid-preview-cli/releases/download/v#{version}/mermaid-preview-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "7709b7245f3b13a5ff26e429d8d8d69712053bf95e194732b3d2088a877bd352"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mermaid-preview-cli"]
    end
  end

  # No zap stanza required
end
