# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmdp" do
  name "mmdp"
  desc "CLI tool for previewing Mermaid diagrams"
  homepage "https://github.com/mxcoppell/mmdp"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmdp"

  on_macos do
    on_intel do
      url "https://github.com/mxcoppell/mmdp/releases/download/v#{version}/mmdp_#{version}_darwin_amd64.tar.gz"
      sha256 "710aa448ea5d26ffc166d4b32ed73a8e4c98391fa81cddecb200f9e93418a219"
    end
    on_arm do
      url "https://github.com/mxcoppell/mmdp/releases/download/v#{version}/mmdp_#{version}_darwin_arm64.tar.gz"
      sha256 "c09e43b62cdbfa5e65acf7330316f15c515fde4da66e94f901ec78612589e8ef"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmdp"]
    end
  end

  # No zap stanza required
end
